sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    browser->>server: {content: "single page app does not reload the full page", date: "2023-09-25T21:50:59.905Z"}
    server-->>browser: HTTP status code 201
    deactivate server
